### ISSUE TITLE
VM shutdown not detected

### ISSUE THREAD

**Issue by Defelo** [SaumonNet/proxmox-nixos#34]
When shutting down a virtual machine (either via Proxmox or from within the vm itself), Proxmox does not detect that the vm has powered off. In this state it is still possible to connect to the console (see screenshot below), and `qm list` reports that the vm is still running. In this state the only way to actually power the machine off is to forcefully stop it. This is also problematic when shutting down or rebooting the host, because systemd would wait for all vms to shutdown (which it fails to detect) and then would time out after 90 seconds.

![image](https://github.com/SaumonNet/proxmox-nixos/assets/41747605/d613f805-7a25-4fe5-a414-4b4769347a50)

I assume this might be related to the following error which occurs whenever a vm is started:
```
Jul 03 14:48:37 nixos QEMU[1460]: qemu-kvm: Unable to connect character device qmp-event: Failed to connect to '/var/run/qmeventd.sock': No such file or directory
```

On my Debian based Proxmox host this socket does exist and seems to be managed by the qmeventd systemd service, which appears to be missing on proxmox-nixos.

**Comment by JulienMalka** [comment]
Thank you for the extensive error report, I have seen this problem in my instance as well. Will have a look pretty soon, as a workaround stopping the VM with the "stop" button after it has reached the poweroff target seems to work for now.
