### ISSUE TITLE
typo @ Readme / Quick Start / With Flakes ?

### ISSUE THREAD

**Issue by thetredev** [SaumonNet/proxmox-nixos#66]
https://github.com/SaumonNet/proxmox-nixos?tab=readme-ov-file#with-flakes states the following:
```nix
{
  ...

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    ...
  };

...
}
```

But below the code snippet, it says
> Do not override the `nixpkgs-stable` input of the flake [...]

So I'm confused. Should we use `nixpkgs-stable` or `nixpkgs-unstable`?

Edit: See https://github.com/SaumonNet/proxmox-nixos/issues/66#issuecomment-2357229073 for a bit more context.

**Comment by Airradda** [comment]
Unless I am also misunderstanding what is being said, It is instructing you not to do the following:
```nix
{
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    proxmox-nixos = {
      url = "github:SaumonNet/proxmox-nixos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
}
```

**Comment by thetredev** [comment]
To me it reads like we're supposed to do it this way using flakes. I'm just wondering about `nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";` in the code block vs. `Do not override the nixpkgs-stable input of the flake [...]` right below the code block. There is no `nixpkgs-stable` in the code block, so why "do not override" it?

Hence I'm guessing either `nixpkgs-unstable` (code block) or `nixpkgs-stable` (warning below code block) is a typo.

**Comment by Airradda** [comment]
The `Do not override the nixpkgs-stable input of the flake [...]`, I believe, refers to the `nixpkgs-stable` input of the `proxmox-nixos` flake, which is located [here](https://github.com/SaumonNet/proxmox-nixos/blob/fdf81ac1018310b2c4ac19be7de6ae84ad1c4957/flake.nix#L3) (currently pinned to `24.05`) and this is indicating that it is the only officially supported release (i.e. not `23.11` or `24.11` in the near future).

**Comment by thetredev** [comment]
Ahhhh gotcha, thanks. Closing.
