### ISSUE TITLE
Can parts of this project help building NixOS VMs for upstream Proxmox ?

### ISSUE THREAD

**Issue by np** [SaumonNet/proxmox-nixos#77]
Before switching to proxmox-nixos, I try to have fully working NixOS VMs on a classic upstream Proxmox.

Which tools from this projet could help ?

**Comment by JulienMalka** [comment]
Just adding on what @codgician said, I think our nixmoxer tool (that can be used to automatically install NixOS VM on a proxmox cluster) can also be useful even out the context of a Proxmox cluster hosted on NixOS.
